name: mrsimulator # overridden at install, so this is for your use with conda env
channels:
  - anaconda
dependencies:
  - numpy=1.13.*
  - setuptools=27.*
  - cython=0.29.*
  - astropy=3.*
  - requests=2.21.*
  - matplotlib=3.0.*
  - fftw=3.3.*
  - openblas
  - pip:
      - flask>=1.1.0
      - plotly>=3.6
      - dash>=0.40
      - dash_bootstrap_components
      - gunicorn
      - mrsimulator>=0.1.2
      - csdmpy>=0.1.2
